### ISSUE TITLE
fix walletconnect

### ISSUE THREAD

**Issue by NoahZinsmeister** [NoahZinsmeister/hypertext#5]
when connected to walletconnect, attempts to buy/sell fail with: `Error: The method eth_sendTransaction does not exist/is not available`

**Comment by mirshko** [comment]
this is related to the ongoing issue with Ethers v5 and Walletconnect. 

@pedrouid is aware and has been working on trying to find a fix. 

`eth_sign` also doesn't work.

**Comment by pedrouid** [comment]
`eth_sign` also doesnt work? yet `personal_sign` works?? This ethers.js bug is getting more and more confusing... Something specific that needs to be done for `eth_` prefixed methods? cc @ricmoo

**Comment by ricmoo** [comment]
These are unfortunately hugely non-standardized.

Various backends support one or the other and some support both signing methods.

Also, some platforms take the parameters in the flipped order... and some “auto sense”, depending on which one “looks” like an address. :(

Le sigh. :)

Is it an ethers.js bug? Is there an issue open for it? I didn’t think there were any issues like this still open...

**Comment by pedrouid** [comment]
It's not an ethers.js bug per se but related to the WalletConnect provider incompatibility with ethers.js which wasn't present before

And according to what we've managed to test both `eth_sendTransaction` and `eth_sign` fail to be resolved but `personal_sign` works fine without causing the error message that @NoahZinsmeister described: 

```
Error: The method eth_sendTransaction does not exist/is not available
```

So my question was why wouldn't the same issue happen with `personal_sign`? Is it exclusive to `eth_` prefixed methods? If so what special requirements are expected from the provider to succeed with these?

I've described more about this issue here: WalletConnect/walletconnect-monorepo#309
